<a href="https://colab.research.google.com/github/Somesh140/ANN/blob/main/RNN/RNN_demo_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## how to do integer encoding

In [1]:
import numpy as np

In [2]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [3]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [6]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [7]:
tokenizer.document_count

11

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [9]:
from keras.utils import pad_sequences

In [10]:
sequences = pad_sequences(sequences,padding='post')

In [11]:
sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

## Sentiment Analysis

In [12]:
from keras.datasets import imdb
from keras import Sequential 
from keras.layers import Dense,SimpleRNN, Flatten

In [13]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [14]:
X_train.shape

(25000,)

In [15]:
X_test.shape

(25000,)

In [16]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [17]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [18]:
print(len(X_train[2]))
print(len(X_train[3]))

141
550


In [19]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [20]:
X_train.shape

(25000, 50)

In [21]:
model= Sequential()
model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False)) # number of nodes input_shape=50  and 1 output we need 
model.add(Dense(1,activation="sigmoid"))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 30s 35ms/step - loss: 0.6938 - accuracy: 0.5074 - val_loss: 0.6944 - val_accuracy: 0.5032
Epoch 2/5
782/782 [==============================] - 29s 37ms/step - loss: 0.6928 - accuracy: 0.5090 - val_loss: 0.6959 - val_accuracy: 0.5021
Epoch 3/5
782/782 [==============================] - 28s 35ms/step - loss: 0.6929 - accuracy: 0.5053 - val_loss: 0.6942 - val_accuracy: 0.5022
Epoch 4/5
782/782 [==============================] - 29s 37ms/step - loss: 0.6930 - accuracy: 0.5035 - val_loss: 0.6940 - val_accuracy: 0.5020
Epoch 5/5
782/782 [==============================] - 27s 35ms/step - loss: 0.6925 - accuracy: 0.5083 - val_loss: 0.6940 - val_accuracy: 0.5069


In [23]:
X_test[0].reshape(1,-1).shape

(1, 50)

In [24]:
pred_test=X_test[0].reshape(1,-1)

#Predictions

In [25]:
model.predict(pred_test)

1/1 [==============================] - 0s 158ms/step


array([[0.49706683]], dtype=float32)

# How to do encodings using keras embeddings

In [26]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [27]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [28]:

tokenizer.fit_on_texts(docs)

In [29]:
len(tokenizer.word_index)

23

In [30]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 1, 2],
 [1, 2],
 [7, 1],
 [8, 9, 3],
 [10, 11, 12, 13],
 [14, 15],
 [16, 3, 17, 4, 5],
 [18, 19],
 [20, 21],
 [22, 23, 1, 2],
 [4, 5]]

In [31]:
sequences = pad_sequences(sequences,padding='post')

In [32]:
sequences

array([[ 6,  1,  2,  0,  0],
       [ 1,  2,  0,  0,  0],
       [ 7,  1,  0,  0,  0],
       [ 8,  9,  3,  0,  0],
       [10, 11, 12, 13,  0],
       [14, 15,  0,  0,  0],
       [16,  3, 17,  4,  5],
       [18, 19,  0,  0,  0],
       [20, 21,  0,  0,  0],
       [22, 23,  1,  2,  0],
       [ 4,  5,  0,  0,  0]], dtype=int32)

In [33]:

from keras.layers import Dense,SimpleRNN, Flatten, Embedding

In [34]:
model=Sequential()
model.add(Embedding(23, output_dim=2,input_length=5)) # 23 unique number of words in corpus input= length of sequence and output= vector size

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              46        
                                                                 
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile('adam','accuracy')

In [36]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 34ms/step
[[[ 0.0485648  -0.02692435]
  [-0.04356867 -0.03150388]
  [ 0.00473595  0.03228357]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]]

 [[-0.04356867 -0.03150388]
  [ 0.00473595  0.03228357]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]]

 [[ 0.02524659  0.02639074]
  [-0.04356867 -0.03150388]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]]

 [[-0.01560974  0.02050413]
  [ 0.03212441 -0.04881437]
  [ 0.0243598   0.00817418]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]]

 [[ 0.02847226 -0.01211726]
  [ 0.00342817 -0.00360014]
  [ 0.04415366 -0.04364833]
  [ 0.04579074  0.04246366]
  [-0.00025254 -0.0050539 ]]

 [[-0.02703246 -0.0139104 ]
  [-0.04539156  0.01432246]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]
  [-0.00025254 -0.0050539 ]]

 [[ 0.02939792 -0.03735323]
  [ 0.0243598   0.00817418]
  [ 0.03963698  0.01680607]
  [-0.014230

## Sentiment Analysis using word embeddings

In [37]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [39]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [40]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [41]:
X_train.shape

(25000, 50)

In [42]:
model = Sequential()
model.add(Embedding(10000,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [43]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 44s 55ms/step - loss: 0.5946 - acc: 0.6512 - val_loss: 0.4470 - val_acc: 0.7947
Epoch 2/5
782/782 [==============================] - 45s 57ms/step - loss: 0.3869 - acc: 0.8312 - val_loss: 0.4254 - val_acc: 0.8058
Epoch 3/5
782/782 [==============================] - 44s 56ms/step - loss: 0.3195 - acc: 0.8688 - val_loss: 0.4444 - val_acc: 0.8062
Epoch 4/5
782/782 [==============================] - 42s 54ms/step - loss: 0.2857 - acc: 0.8872 - val_loss: 0.5129 - val_acc: 0.7965
Epoch 5/5
782/782 [==============================] - 44s 56ms/step - loss: 0.2580 - acc: 0.9015 - val_loss: 0.4956 - val_acc: 0.7966


#Predictions

In [44]:
test_data = X_test[0][0:50].reshape(1,-1)

In [45]:
model.predict(test_data)

1/1 [==============================] - 0s 131ms/step


array([[0.19055574]], dtype=float32)